/*
* Contains keys for identifying data generated by the GPS subsystem
* Author: Liam Hebert
* Date: June 26 2019
*/

enum GPSKeys {
  type = 0,
  time_stamp = 1,
  latitude = 2,
  longitude = 3,
  num_sats = 4,
  horizontal_dilution = 5,
  altitude = 6
};
