/*
* Contains keys for identifying data generated by the power subsystem
* Author: Andrew Way
* Date: June 17 2019
*/


enum PowerKeys {
  current_sensor_1 = 1,
  current_sensor_2 = 2,
  battery_level = 3
};